* Meta-P is stolen:

dconf write /org/gnome/settings-daemon/plugins/media-keys/active false


* Booting

USB is mounted read-only:

sudo mount -o remount,rw /media/nik/NIXDRIVE


* UEFI/refind dance

Notes re: Ubuntu on a Macbook air (Ubuntu 14.04 on MacBookAir6,1).

I've installed Ubuntu from a bootable USB drive. It installed in non-UEFI mode. 

Symptoms: fails to boot randomly, boots with nosmp boot option, but only has one cpu available.

I've tried BootRepair, which messed up my grub even more.

I've read http://www.rodsbooks.com/efi-bootloaders/grub2.html, lots of info. Parts of it to summarize below.

rEFInd: scans all fat and hfs partitions for /boot/efi/*.efi files and shows them in the menu.

How to create an .efi file is a bit of e mystery. I've tried grub-mkimage, got an invalid file.

What worked: having a file on /dev/sda1 - /EFI/grub/grubx64.efi, AND a grub.cfg in the same dir. grub.cfg was generated with update-grub. The .efi file was probably generated by boot-repair (but it failed to repair the efi boot completely, and I had to fix it manually - by doing update-grub and placing the resulting grub.cfg into the right place). I think the /EFI/grub directory also needs to have the other files - fonts, locale, etc. Not sure where they come from.

Overall it was a lot of trial and error, and I still don't completely understand how I made it work (if only there was a distro/script that 'just worked' ;)).
